package com.example.springboot.dto;

import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;


@JacksonXmlRootElement(localName = "transaccion")
public class Dto {

    @JacksonXmlProperty(localName = "USUARIO")
    private String usuario;
    @JacksonXmlProperty(localName = "CLAVE")
    private String clave;
    
    @JacksonXmlProperty(localName = "ENCDescripcion")
    private String ENCDescripcion;
    @JacksonXmlProperty(localName = "GMVCodigo")
    private String GMVCodigo;
    @JacksonXmlProperty(localName = "MOVCodigo")
    private String MOVCodigo;
    @JacksonXmlProperty(localName = "movimiento")
    private String movimiento;
    @JacksonXmlProperty(localName = "USUCodigo")
    private String USUCodigo;
    @JacksonXmlProperty(localName = "CAJCodigo")
    private String CAJCodigo;
    @JacksonXmlProperty(localName = "IDEMP")
    private String IDEMP;
    @JacksonXmlProperty(localName = "ALMCodigo")
    private String ALMCodigo;
    @JacksonXmlProperty(localName = "ALMNombre")
    private String ALMNombre;
    @JacksonXmlProperty(localName = "MONCodigo")
    private String MONCodigo;
    @JacksonXmlProperty(localName = "ENCFechaTrx")
    private String ENCFechaTrx;
    @JacksonXmlProperty(localName = "ENCHoraTrx")
    private String ENCHoraTrx;
    @JacksonXmlProperty(localName = "ENCModo")
    private String ENCModo;
    @JacksonXmlProperty(localName = "ENCTipoProc")
    private String ENCTipoProc;
    @JacksonXmlProperty(localName = "ENCConsTrx")
    private String ENCConsTrx;
    @JacksonXmlProperty(localName = "ENCTasaConversion")
    private String ENCTasaConversion;
    @JacksonXmlProperty(localName = "ENCTotalReferencias")
    private String ENCTotalReferencias;
    @JacksonXmlProperty(localName = "ENCBruto")
    private String ENCBruto;
    @JacksonXmlProperty(localName = "ENCDescuento")
    private String ENCDescuento;
    @JacksonXmlProperty(localName = "ENCPagNoVenta")
    private String ENCPagNoVenta;
    @JacksonXmlProperty(localName = "ENCVenta")
    private String ENCVenta;
    @JacksonXmlProperty(localName = "ENCImpuestos")
    private String ENCImpuestos;
    @JacksonXmlProperty(localName = "ENCComision")
    private String ENCComision;
    @JacksonXmlProperty(localName = "ENCNeto")
    private String ENCNeto;
    @JacksonXmlProperty(localName = "ENCRecaudo")
    private String ENCRecaudo;
    @JacksonXmlProperty(localName = "ENCImpuestoAsumido")
    private String ENCImpuestoAsumido;
    @JacksonXmlProperty(localName = "ENCPuntos")
    private String ENCPuntos;
    @JacksonXmlProperty(localName = "ENCEstadoLinea")
    private String ENCEstadoLinea;
    @JacksonXmlProperty(localName = "ENCRespuesta")
    private String ENCRespuesta;
    @JacksonXmlProperty(localName = "ENCDescRespuesta")
    private String ENCDescRespuesta;

    @JacksonXmlProperty(localName = "ICPPresentacion")
    private String ICPPresentacion;
    @JacksonXmlProperty(localName = "ICPDescripcion")
    private String ICPDescripcion;
    @JacksonXmlProperty(localName = "ICPCadena")
    private String ICPCadena;
    @JacksonXmlProperty(localName = "ICPLetra")
    private String Icpletra;

    @JacksonXmlProperty(localName = "ICPPresentacion")
    private String icppresentacion;
    @JacksonXmlProperty(localName = "ICPDescripcion")
    private String icpdescripcion;
    @JacksonXmlProperty(localName = "ICPCadena")
    private String icpcadena;
    @JacksonXmlProperty(localName = "ICPLetra")
    private String icpletra;

    @JacksonXmlProperty(localName = "REFCodClasificacion")
    private String REFCodClasificacion;
    @JacksonXmlProperty(localName = "REFCodigo1")
    private String REFCodigo1;
    @JacksonXmlProperty(localName = "REFCodigo2")
    private String REFCodigo2;
    @JacksonXmlProperty(localName = "REFNombreCorto")
    private String REFNombreCorto;
    @JacksonXmlProperty(localName = "REFNombreLargo")
    private String REFNombreLargo;
    @JacksonXmlProperty(localName = "CARCodigo1")
    private String CARCodigo1;
    @JacksonXmlProperty(localName = "REFPrecioLista")
    private String REFPrecioLista;
    @JacksonXmlProperty(localName = "IRFBruto")
    private String IRFBruto;
    @JacksonXmlProperty(localName = "IRFDescuento")
    private String IRFDescuento;
    @JacksonXmlProperty(localName = "IRFPago")
    private String IRFPago;
    @JacksonXmlProperty(localName = "IRFCantidad")
    private String IRFCantidad;
    @JacksonXmlProperty(localName = "IRFValorImpuesto")
    private String IRFValorImpuesto;
    @JacksonXmlProperty(localName = "IRFImpuesto")
    private String IRFImpuesto;
    @JacksonXmlProperty(localName = "REFEsCombo")
    private String REFEsCombo;
    @JacksonXmlProperty(localName = "REFUltimoCosto")
    private String REFUltimoCosto;
    @JacksonXmlProperty(localName = "PRVCodigo")
    private String PRVCodigo;
    @JacksonXmlProperty(localName = "REFManejaLotes")
    private String REFManejaLotes;
    @JacksonXmlProperty(localName = "REFFactorConversion")
    private String REFFactorConversion;
    @JacksonXmlProperty(localName = "REFInventario")
    private String REFInventario;
    @JacksonXmlProperty(localName = "REFEsParaVenta")
    private String REFEsParaVenta;
    @JacksonXmlProperty(localName = "estado")
    private String estado;
    @JacksonXmlProperty(localName = "IRFPagNoVenta")
    private String IRFPagNoVenta;
    @JacksonXmlProperty(localName = "IRFVenta")
    private String IRFVenta;
    @JacksonXmlProperty(localName = "IRFValorImpuestoNeto")
    private String IRFValorImpuestoNeto;
    @JacksonXmlProperty(localName = "IRFComision")
    private String IRFComision;
    @JacksonXmlProperty(localName = "IRFNeto")
    private String IRFNeto;
    @JacksonXmlProperty(localName = "REFCodigoIngresado")
    private String REFCodigoIngresado;
    @JacksonXmlProperty(localName = "RREFPuntos")
    private String RREFPuntos;

    @JacksonXmlProperty(localName = "ICPPresentacion")
    private String ICPpresentacion;
    @JacksonXmlProperty(localName = "ICPDescripcion")
    private String ICPdescripcion;
    @JacksonXmlProperty(localName = "ICPCadena")
    private String ICPcadena;
    @JacksonXmlProperty(localName = "ICPLetra")
    private String ICPletra;

}