apiVersion: v1
kind: Service
metadata:
    name: qacomerssia
spec:

    type: ClusterIP
    ports:
        - name: http
          nodePort: null
          port: 8080
          targetPort: 8080
          protocol: TCP
    selector:
        app: qacomerssia