//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.10 at 08:32:35 PM COT 
//


package com.example.springboot.wsdl.mapping;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="pi_sIdemp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="pi_sUsuarioWS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="pi_sClaveWS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="pi_sNombreArchivo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="pi_sExtencion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="pi_sEnvio" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "piSIdemp",
    "piSUsuarioWS",
    "piSClaveWS",
    "piSNombreArchivo",
    "piSExtencion",
    "piSEnvio"
})
@XmlRootElement(name = "wm_GuardarArchivoBatch")
public class WmGuardarArchivoBatch {

    @XmlElement(name = "pi_sIdemp")
    protected String piSIdemp;
    @XmlElement(name = "pi_sUsuarioWS")
    protected String piSUsuarioWS;
    @XmlElement(name = "pi_sClaveWS")
    protected String piSClaveWS;
    @XmlElement(name = "pi_sNombreArchivo")
    protected String piSNombreArchivo;
    @XmlElement(name = "pi_sExtencion")
    protected String piSExtencion;
    @XmlElement(name = "pi_sEnvio")
    protected byte[] piSEnvio;

    /**
     * Gets the value of the piSIdemp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPiSIdemp() {
        return piSIdemp;
    }

    /**
     * Sets the value of the piSIdemp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPiSIdemp(String value) {
        this.piSIdemp = value;
    }

    /**
     * Gets the value of the piSUsuarioWS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPiSUsuarioWS() {
        return piSUsuarioWS;
    }

    /**
     * Sets the value of the piSUsuarioWS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPiSUsuarioWS(String value) {
        this.piSUsuarioWS = value;
    }

    /**
     * Gets the value of the piSClaveWS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPiSClaveWS() {
        return piSClaveWS;
    }

    /**
     * Sets the value of the piSClaveWS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPiSClaveWS(String value) {
        this.piSClaveWS = value;
    }

    /**
     * Gets the value of the piSNombreArchivo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPiSNombreArchivo() {
        return piSNombreArchivo;
    }

    /**
     * Sets the value of the piSNombreArchivo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPiSNombreArchivo(String value) {
        this.piSNombreArchivo = value;
    }

    /**
     * Gets the value of the piSExtencion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPiSExtencion() {
        return piSExtencion;
    }

    /**
     * Sets the value of the piSExtencion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPiSExtencion(String value) {
        this.piSExtencion = value;
    }

    /**
     * Gets the value of the piSEnvio property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getPiSEnvio() {
        return piSEnvio;
    }

    /**
     * Sets the value of the piSEnvio property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setPiSEnvio(byte[] value) {
        this.piSEnvio = value;
    }

}
