//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.18 at 03:36:59 PM COT 
//


package com.example.springboot.wsdl.mapping;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="pi_sIdemp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="pi_iNumeroCalle" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="pi_iNumeroCarrera" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="pi_iNumeroAdicional" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "piSIdemp",
    "piINumeroCalle",
    "piINumeroCarrera",
    "piINumeroAdicional"
})
@XmlRootElement(name = "wm_pb_devolver_Zona")
public class WmPbDevolverZona {

    @XmlElement(name = "pi_sIdemp")
    protected String piSIdemp;
    @XmlElement(name = "pi_iNumeroCalle")
    protected int piINumeroCalle;
    @XmlElement(name = "pi_iNumeroCarrera")
    protected int piINumeroCarrera;
    @XmlElement(name = "pi_iNumeroAdicional")
    protected int piINumeroAdicional;

    /**
     * Gets the value of the piSIdemp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPiSIdemp() {
        return piSIdemp;
    }

    /**
     * Sets the value of the piSIdemp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPiSIdemp(String value) {
        this.piSIdemp = value;
    }

    /**
     * Gets the value of the piINumeroCalle property.
     * 
     */
    public int getPiINumeroCalle() {
        return piINumeroCalle;
    }

    /**
     * Sets the value of the piINumeroCalle property.
     * 
     */
    public void setPiINumeroCalle(int value) {
        this.piINumeroCalle = value;
    }

    /**
     * Gets the value of the piINumeroCarrera property.
     * 
     */
    public int getPiINumeroCarrera() {
        return piINumeroCarrera;
    }

    /**
     * Sets the value of the piINumeroCarrera property.
     * 
     */
    public void setPiINumeroCarrera(int value) {
        this.piINumeroCarrera = value;
    }

    /**
     * Gets the value of the piINumeroAdicional property.
     * 
     */
    public int getPiINumeroAdicional() {
        return piINumeroAdicional;
    }

    /**
     * Sets the value of the piINumeroAdicional property.
     * 
     */
    public void setPiINumeroAdicional(int value) {
        this.piINumeroAdicional = value;
    }

}
